---
title: "Portafolio_in_R_Asesoria"
author: "Edgar Sigfrido Soto Aparicio"
date: "3/15/2022"
output: html_document
---
1. Librerias
```{r}
library(tidyverse)
library(quantmod)
library(PortfolioAnalytics)
library(fPortfolio)
library(PerformanceAnalytics)
library(readr)
library(psych)
```

2. Datos
```{r}
Equity <- c("NVS", "AMZN", "WM", "TSLA", "NVDA", "GOOG")
getSymbols(Equity, from=as.Date("2018-02-05"), to=Sys.Date())
Novart <- Ad(NVS)
Amz <- Ad(AMZN)
WasMan <- Ad(WM)
Tesl <- Ad(TSLA)
Nvdia <- Ad(NVDA)
Goog <- Ad(GOOG)
EquityAd <- merge.xts(Novart, Amz, WasMan, Tesl, Nvdia, Goog,
                       join = "inner") #interseccion, solo toma los días donde todos                                            cotizan
Equity_Rend_log <- Return.calculate(EquityAd, method = "log")[-1] #logN(x2/x1)
```
```{r}
chartSeries(Equity_Rend_log$AMZN.Adjusted)
chartSeries(EquityAd)
cor.plot(Equity_Rend_log)
var_cov <- as.data.frame(var(Equity_Rend_log)) 
```

3. Portafolio
```{r}
Specs_Portfolio <- portfolio.spec(Activos) #genera una lista con los objetivos y restricciones
Specs_Portfolio <- add.constraint(Specs_Portfolio,type = "full_investment")
Specs_Portfolio <- add.constraint(Specs_Portfolio,type = "long_only")
Specs_Portfolio <- 
Specs_Portfolio <- add.constraint(Specs_Portfolio, type = "5%")
Specs_Portfolio <- add.objective(Specs_Portfolio, type = "risk", name = "VaR")
Specs_Portfolio <- add.objective(Specs_Portfolio,type = "return",name = "mean") #optimizar a Sharp, en este casdo se debe quitar en "risk"
Specs_Portfolio
```

```{r}
Optimum_Portfolio <- optimize.portfolio(Rend, Specs_Portfolio) 
#en caso de que no converja, usar ", optimize_method = random"
```

```{r}
chart.Weights(Optimum_Portfolio)
```
```{r}
# nuevo objeto para los rendimientos del port
RendOptPort <- Return.portfolio(Rend,
                                extractWeights(Optimum_Portfolio))
plot(density(RendOptPort))

VaR(RendOptPort)*sqrt(1)*1000000

charts.PerformanceSummary(RendOptPort)
```

```{r}
table.AnnualizedReturns(RendOptPort) #por default esta anualizado
table.AnnualizedReturns(Rend)
```
expected Shortfall
```{r}
ES(RendOptPort)
#dentro de ese 1/20, cuanto vas a perder en promedio pasando el limite del VaR
```


optimizar el 





